# Generated by Django 4.2.6 on 2023-10-24 05:13

import bingo_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolillero', models.CharField(default=bingo_app.models.default_bolillero, max_length=200, validators=[django.core.validators.RegexValidator('^([1-9][0-9]?|90)(,[1-9][0-9]?|,90)*$', 'Introduzca una lista de números del 1 al 90 separados por comas.')])),
                ('numero_sorteado', models.IntegerField(blank=True, null=True)),
                ('numeros_sorteados', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.RegexValidator('^([1-9][0-9]?|90)(,[1-9][0-9]?|,90)*$', 'Introduzca una lista de números del 1 al 90 separados por comas.')])),
            ],
        ),
    ]
