# Generated by Django 4.2.6 on 2023-11-08 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0002_alter_sorteo_bolillero'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_numeros', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^([1-9][0-9]?|[1-9][0-9]{2}|[1-9][0-9]{2}|900)$', 'Introduzca un rango de números del 1 al 900 separados por un guion (-).')])),
                ('numero_sorteado', models.IntegerField(blank=True, null=True)),
                ('numeros_sorteados', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.RegexValidator('^([1-9][0-9]?|90)(,[1-9][0-9]?|,90)*$', 'Introduzca una lista de números del 1 al 90 separados por comas.')])),
            ],
        ),
    ]
