# Generated by Django 4.2.6 on 2023-11-08 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0003_customsorteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsorteo',
            name='rango_numeros',
        ),
        migrations.AddField(
            model_name='customsorteo',
            name='numero_fin',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(900)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customsorteo',
            name='numero_inicio',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(899)]),
            preserve_default=False,
        ),
    ]
