# Generated by Django 4.2.6 on 2023-11-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0004_remove_customsorteo_rango_numeros_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSorteo',
        ),
    ]
