# Generated by Django 4.2.6 on 2023-11-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0005_delete_customsorteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_original', models.TextField()),
                ('numeros_sorteados', models.TextField()),
            ],
        ),
    ]
