# Generated by Django 4.2.6 on 2023-11-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0006_numeros'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroSorteado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_sorteo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Numeros',
        ),
    ]
