# Generated by Django 4.2.6 on 2023-11-08 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0007_numerosorteado_delete_numeros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteo_Numeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_maximo', models.IntegerField()),
                ('bolillero', models.CharField(default=None, max_length=400, validators=[django.core.validators.RegexValidator('^([1-9][0-9]?|90)(,[1-9][0-9]?|,90)*$', 'Introduzca una lista de números del 1 al 90 separados por comas.')])),
                ('numero_sorteado', models.IntegerField(blank=True, null=True)),
                ('numeros_sorteados', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.RegexValidator('^([1-9][0-9]?|90)(,[1-9][0-9]?|,90)*$', 'Introduzca una lista de números del 1 al 90 separados por comas.')])),
            ],
        ),
        migrations.DeleteModel(
            name='NumeroSorteado',
        ),
    ]
